# ????????? MySQL ???? ??????
spring.datasource.url=jdbc:mysql://localhost:3306/ nzk_stuffpanel?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate ?????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ??????????? SQL ????????
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

cloudinary.cloud-name=dzrbma2st
cloudinary.api-key=484965244899611
cloudinary.api-secret=MN5h0SKPxy4hLN5G8Q2Fk5FG1EE