spring.application.name=NZKStuffPanel

spring.datasource.url=jdbc:${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

cloudinary.cloud-name=dzrbma2st
cloudinary.api-key=484965244899611
cloudinary.api-secret=MN5h0SKPxy4hLN5G8Q2Fk5FG1EE

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
