spring.application.name=NZKStuffPanel

spring.datasource.url=jdbc:${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=false

# Thymeleaf Configuration
spring.thymeleaf.cache=true
spring.web.resources.cache.period=86400
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.jpa.properties.hibernate.jdbc.batch_size=15
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.jpa.open-in-view=false


server.forward-headers-strategy=native
server.tomcat.redirect-context-root=true

server.use-forward-headers=true

cloudinary.cloud-name=dzrbma2st
cloudinary.api-key=484965244899611
cloudinary.api-secret=MN5h0SKPxy4hLN5G8Q2Fk5FG1EE

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

server.compression.enabled=true
server.compression.mime-types=text/html,text/css,text/javascript,application/json

spring.datasource.hikari.maximumPoolSize=3
spring.datasource.hikari.minimumIdle=1
spring.datasource.hikari.idleTimeout=300000

spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true



